### ISSUE TITLE
SEARCH ENGINE OPTIMIZATION - [0.5]

### ISSUE THREAD

**Issue by arfa** [wassim-arfa/commerce-mui#48]
https://nextjs.org/learn/seo/introduction-to-seo

- [x] Introduction to SEO
- [x] Crawling and Indexing
- [x] Status Codes
- [x] Rendering and Ranking
- [x] Performance & Core Web Vitals
- [x] Improving your Core Web Vitals
- [x] Monitoring your Core Web Vitals

**Comment by fabform** [comment]
Handy alternative list of [alternative search engines](https://fabform.io/a/alternative-search-engines)
